[workspace]
resolver = "2"
members = [
    "builder",
    "agent",
    "c2r2-server",
    "stealer-dll",
    "ransomware-dll",
    "dropper-rust",
    "stages/ester",
    "stages/javelin",
    "stages/stage0"
]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = "z"  # Optimizar para tamaño
